source 'https://github.com/CocoaPods/Specs.git'

target 'CMBReactiveSocial', :exclusive => true do
  pod "CMBReactiveSocial", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "CMBReactiveSocial", :path => "../"

  
end
